data_dir: ""
driver: "DSO3000"  # DSO3000 or DSO1000
time_scale: 2e-9
sampling_rate: 1e9
channels:
  - ch: 1
    label: "Detector"
    v_scale: 50.0E-3  # DSO vertical scale in Volts/div
    coupling: "DC"
    bw_limit: 0  # 1 for bandwidth limit ~25MHz
    probe_attn: 1  # Probe attenuation x 1 | 10 | 100 | 1000
    invert: 0  # 1 = Invert ON, 0 = Invert OFF
  - ch: 2
    label: "Preamp"
    v_scale: 0.2  # DSO vertical scale in Volts/div
    coupling: "DC"  # DC | AC | GND
    bw_limit: 0  # 1 for bandwidth limit ~25MHz
    probe_attn: 1  # Probe attenuation x 1 | 10 | 100 | 1000
    invert: 0  # 1 = Invert ON, 0 = Invert OFF
trigger_mode: "EDGE"  # EDGE, PULSE, TV
trigger_source: "EXT"  # CH1, CH2, Ext
trigger_slope: "POS"  # NEG or POS
trigger_level: 0.75  # EDGE Trigger level in volts
trigger_coupling: "DC"  # DC | AC | LF | HF
trigger_sweep: "NORMAL"  # NORMAL or AUTO
trigger_force: 1  # Force software trigger if 1
